# Generated by Django 4.0.4 on 2022-06-13 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0006_remove_task_project_id_remove_task_tag_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnattribute',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 12, 25, 4, 856034)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 12, 25, 4, 857035)),
        ),
    ]
