# Generated by Django 4.0.4 on 2022-06-13 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0007_remove_columnattribute_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnattribute',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.user'),
        ),
        migrations.AddField(
            model_name='permission',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.user'),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 12, 33, 46, 816936)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.tag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 12, 33, 46, 817937)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.task'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.project'),
        ),
        migrations.AlterField(
            model_name='taskattribute',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.task'),
        ),
        migrations.AlterField(
            model_name='tasktag',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.tag'),
        ),
        migrations.AlterField(
            model_name='tasktag',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.task'),
        ),
    ]
