# Generated by Django 4.0.4 on 2022-06-14 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagementApp', '0010_remove_task_user_id_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 17, 9, 8, 901449)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.tag'),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 17, 9, 8, 902448)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='tag_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskattribute',
            name='task_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktag',
            name='tag_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktag',
            name='task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskManagementApp.task'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
