# Generated by Django 4.0.4 on 2022-06-14 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0013_alter_columnattribute_date_alter_comment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnattribute',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 17, 15, 27, 777855)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 17, 15, 27, 779853)),
        ),
    ]
