# Generated by Django 4.0.4 on 2022-06-15 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0017_alter_columnattribute_date_alter_comment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 10, 12, 996529)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 12, 10, 12, 996529)),
        ),
    ]
