# Generated by Django 4.0.4 on 2022-06-16 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0022_alter_columnattribute_date_alter_comment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 6, 22, 275378)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 6, 22, 277377)),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateField(null=True),
        ),
    ]
