# Generated by Django 4.0.4 on 2022-06-16 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0023_alter_columnattribute_date_alter_comment_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 31, 4, 68645)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 31, 4, 72643)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
