# Generated by Django 4.0.4 on 2022-06-16 11:00

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0025_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 30, 14, 265005)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='unique_random_id',
            field=models.CharField(blank=True, default=uuid.UUID('3a186ae0-64ea-4608-9db8-22dff0761f07'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 30, 14, 267004)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, default=uuid.UUID('a5a2a81e-d5c0-4091-8185-7d83ce80f3e7'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(blank=True, default=uuid.UUID('0175b52f-57ac-4640-8e9c-6808ca8b46bc'), max_length=100, unique=True),
        ),
    ]
