# Generated by Django 4.0.4 on 2022-06-16 11:00

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0026_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 30, 55, 529429)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='unique_random_id',
            field=models.CharField(blank=True, default=uuid.UUID('f2b31014-291d-4d63-87dd-9c91567329e1'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 30, 55, 530429)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, default=uuid.UUID('7860027c-4333-476d-9c2e-5200a9f67d17'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(blank=True, default=uuid.UUID('c945ff6b-7556-4575-acfa-1ab0b2797309'), max_length=100, null=True, unique=True),
        ),
    ]
