# Generated by Django 4.0.4 on 2022-06-16 11:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0027_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 32, 26, 906085)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='unique_random_id',
            field=models.CharField(blank=True, default=uuid.UUID('21aaf4e0-ae51-4e58-a793-b6732d3d4ff3'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 32, 26, 907085)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, default=uuid.UUID('37041dc4-bb23-4bdf-8d81-48724265bf96'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(max_length=122, null=True),
        ),
    ]
