# Generated by Django 4.0.4 on 2022-06-16 11:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0028_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 34, 48, 975246)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='unique_random_id',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 34, 48, 977245)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=uuid.UUID('42eab751-74fb-426e-bf5c-7dd8f6ba89c6'), max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
