# Generated by Django 4.0.4 on 2022-06-16 11:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0029_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 36, 0, 336940)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 36, 0, 338938)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=uuid.UUID('2fce0749-de77-400f-b43d-129204537a01'), max_length=122, unique=True),
        ),
    ]
