# Generated by Django 4.0.4 on 2022-06-16 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0036_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 17, 45, 3, 527509)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='unique_random_id',
            field=models.CharField(default='59512', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 17, 45, 3, 528508)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='59512', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default='59512', max_length=122, unique=True),
        ),
    ]
