# Generated by Django 4.0.4 on 2022-06-16 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0040_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 17, 50, 39, 489537)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='unique_random_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 17, 50, 39, 491536)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
