# Generated by Django 4.0.4 on 2022-06-21 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagementApp', '0042_alter_columnattribute_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='createUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 16, 15, 2, 704065)),
        ),
        migrations.AlterField(
            model_name='columnattribute',
            name='unique_random_id',
            field=models.SlugField(default='10369', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 16, 15, 2, 706061)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.SlugField(default='10369', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.SlugField(default='10369', max_length=6, unique=True),
        ),
    ]
